owncloud:
  image: owncloud:fpm
  links:
    - owncloud-db
  tags:
    - doroleim
    - online
  autoredeploy: true
  restart: always
  net: bridge
  mem_limit: 1g
  memswap_limit: 1g
  
owncloud-db:
  image: postgres:9.5
  tags:
    - doroleim
    - online
  autoredeploy: true
  restart: always
  net: bridge
  mem_limit: 1g
  memswap_limit: 1g
