owncloud:
  image: 'owncloud:fpm'
  autoredeploy: true
  links:
    - owncloud-db
  mem_limit: 1024m
  memswap_limit: 1024m
  restart: always
  tags:
    - doroleim
    - online
owncloud-db:
  image: 'postgres:9.5'
  autoredeploy: true
  mem_limit: 1024m
  memswap_limit: 1024m
  restart: always
  tags:
    - doroleim
    - online

